### ISSUE TITLE
Cara maketin ke. Apk gimana ya ?

### ISSUE THREAD

**Issue by azispratama92** [azzamsa/Ask-Indonesia-UserWords#1]
Mungkinkah dipaketkan ke dalam berkas *.apk seperti pada language_pack di repository f-droid?

**Comment by azzamsa** [comment]
@azispratama92 [on progress](https://github.com/AnySoftKeyboard/LanguagePack/issues/118) ... be patient :)

**Comment by azzamsa** [comment]
https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.indonesian
